[package]
name = "seli-vector-db"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "2.0.1"
rand = "0.9.2"
anyhow = "1.0"
thiserror = "2.0.17"

[dev-dependencies]
criterion = "0.8.0"
hnsw = "0.11.0"
space = "0.17.0"

[[bench]]
name = "search_bench"
harness = false
