[package]
name = "vector_db"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.2"

[dev-dependencies]
criterion = "0.8.0"
hnsw = "0.11.0"
space = "0.17.0"

[[bench]]
name = "search_bench"
harness = false
